version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: gunicorn backend.config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - media_data:/app/backend/media
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - backend-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run build
    volumes:
      - ./frontend:/app/frontend
      - frontend_build:/app/frontend/build
    networks:
      - backend-net

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html
      - media_data:/usr/share/nginx/html/media
    depends_on:
      - frontend
      - backend
    networks:
      - backend-net

volumes:
  postgres_data:
  media_data:
  frontend_build:

networks:
  backend-net:
    driver: bridge